name: Test URL
on:
  schedule:
    - cron: "0 2 * * 0" # Weekly on Sundays at 02:00

jobs:
  build:
    strategy:
      matrix:
        package: [desktop, ros-base]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Verify shorten-URL
        env:
          PACKAGE_VERSION: ${{ matrix.package }}
        run: |
          curl -I -Ls -o run.sh -w %{url_effective} http://u.ty0.jp/ros-melodic-$PACKAGE_VERSION | tee url.txt
          diff run.sh ros-melodic-$PACKAGE_VERSION.sh
          diff -w url.txt <(echo https://raw.githubusercontent.com/Tiryoh/ros_setup_scripts_ubuntu/master/ros-melodic-$PACKAGE_VERSION.sh)
