name: Test Scripts
on:
  push:
    branches:
      - master
    paths:
      - "**.sh"
  pull_request:
    branches:
      - master
    paths:
      - "**.sh"
  schedule:
    - cron: "0 2 * * 0" # Weekly on Sundays at 02:00

jobs:
  kinetic:
    strategy:
      matrix:
        package: [desktop, ros-base]
    env:
      ROS_DISTRO: kinetic
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@master

      - name: Install Test
        env:
          PACKAGE_VERSION: ${{ matrix.package }}
        run: |
          ./ros-${ROS_DISTRO}-${PACKAGE_VERSION}.sh
  melodic:
    strategy:
      matrix:
        package: [desktop, ros-base]
    env:
      ROS_DISTRO: melodic
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master

      - name: Install Test
        env:
          PACKAGE_VERSION: ${{ matrix.package }}
        run: |
          ./ros-${ROS_DISTRO}-${PACKAGE_VERSION}.sh
